language: php

matrix:
    include:
        - php: 8.1
        - php: 8.2
        - php: 8.3
        - php: 8.4
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpcs --standard=psr2 --warning-severity=0 src/
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi